/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.MrbCliente;
import dao.ClientesDAO;
import bean.MrbVenda;
import dao.VendaDAO;
import bean.MrbPagamento;
import dao.PagamentosDAO;
import java.util.List;
import tools.Util;

/**
 *
 */
public class JDlgMrbVenda extends javax.swing.JDialog {

    private boolean incluir;

    /**
     * Creates new form JDlgMrbVenda
     */
    public JDlgMrbVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Venda");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas, jBtnAlterar, jBtnExcluir, jBtnConfirmar, jBtnCancelar);
        ClientesDAO clientesDAO = new ClientesDAO();
        PagamentosDAO vendedoresDAO = new PagamentosDAO();
        List clientes = (List) clientesDAO.listAll();
        for (int i = 0; i < clientes.size(); i++) {
            jCboMrbCliente.addItem((MrbCliente) clientes.get(i));
        }
        List vendedores = (List) vendedoresDAO.listAll();
        for (int i = 0; i < vendedores.size(); i++) {
            jCboMrbPagamentos.addItem((MrbPagamento) vendedores.get(i));
        }
        try {
            javax.swing.text.MaskFormatter mascaraData = new javax.swing.text.MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter(' ');
            jFmtMrbDataVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
    }

    public MrbVenda viewBean() {
        MrbVenda mrbVenda = new MrbVenda();
        int codigo = Util.strToInt(jTxtMrbCodigo.getText());
        mrbVenda.setMrbIdVenda(codigo);
        mrbVenda.setMrbCliente((MrbCliente) jCboMrbCliente.getSelectedItem());
        mrbVenda.setMrbPagamento((MrbPagamento) jCboMrbPagamentos.getSelectedItem());
        mrbVenda.setMrbDataVenda(Util.strToDate(jFmtMrbDataVendas.getText()));
        mrbVenda.setMrbValorTotal(Util.strToDouble(jTxtMrbTotal.getText()));
        mrbVenda.setMrbTipoEntrega(jTxtMrbTipo.getText());
        mrbVenda.setMrbStatusVenda(jTxtMrbStatus.getText());
        return mrbVenda;
    }

    public void beanView(MrbVenda mrbVenda) {
    jTxtMrbCodigo.setText(Util.intToStr(mrbVenda.getMrbIdVenda()));
    jCboMrbCliente.setSelectedItem(mrbVenda.getMrbCliente());
    jCboMrbPagamentos.setSelectedItem(mrbVenda.getMrbPagamento());
    jFmtMrbDataVendas.setText(Util.dateToStr(mrbVenda.getMrbDataVenda()));
    jTxtMrbTotal.setText(Util.doubleToStr(mrbVenda.getMrbValorTotal()));
    jTxtMrbTipo.setText(mrbVenda.getMrbTipoEntrega());
    jTxtMrbStatus.setText(mrbVenda.getMrbStatusVenda());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPanelMrbPainel = new javax.swing.JScrollPane();
        jTblMrbTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCboMrbPagamentos = new javax.swing.JComboBox<MrbPagamento>();
        jTxtMrbCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtMrbTotal = new javax.swing.JTextField();
        jFmtMrbDataVendas = new javax.swing.JFormattedTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterarProd = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtMrbStatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtMrbTipo = new javax.swing.JTextField();
        jCboMrbCliente = new javax.swing.JComboBox<MrbCliente>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Clientes");

        jLabel5.setText("Data Vendas");

        jLabel7.setText("Pagamentos");

        jTblMrbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelMrbPainel.setViewportView(jTblMrbTabela);

        jLabel1.setText("Codigo");

        jTxtMrbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMrbCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        jFmtMrbDataVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtMrbDataVendasActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrot.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chest.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apple.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });

        jLabel8.setText("Status da Venda");

        jLabel9.setText("Tipo da Entrega");

        jCboMrbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboMrbClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtMrbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCboMrbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jCboMrbPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtMrbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFmtMrbDataVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMrbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTxtMrbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanelMrbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirProd)
                            .addComponent(jBtnExcluirProd)
                            .addComponent(jBtnAlterarProd))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMrbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboMrbPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboMrbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtMrbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFmtMrbDataVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtMrbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtMrbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelMrbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jBtnIncluirProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluirProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtMrbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMrbCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMrbCodigoActionPerformed

    private void jFmtMrbDataVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtMrbDataVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtMrbDataVendasActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        VendaDAO mrbVendaDAO = new VendaDAO();
        if (incluir) {
            mrbVendaDAO.insert(viewBean());
        } else {
            mrbVendaDAO.update(viewBean());
        }
        Util.habilitar(false, jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas, jBtnConfirmar, jBtnCancelar, jBtnAlterar, jBtnExcluir);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgMrbVendaPesquisar jDlgMrbVendaPesquisar = new JDlgMrbVendaPesquisar(null, true);
        jDlgMrbVendaPesquisar.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Util.habilitar(true, jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas);
        jTxtMrbCodigo.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Util.habilitar(true, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnExcluir, jBtnIncluir, jBtnAlterar);
        jTxtMrbTotal.grabFocus();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Excluir?") == true) {
            VendaDAO mrbVendaDAO = new VendaDAO();
            mrbVendaDAO.delete(viewBean());
            Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnExcluir);
            Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
            Util.limpar(jTxtMrbCodigo, jTxtMrbCodigo, jTxtMrbTotal, jCboMrbCliente, jCboMrbPagamentos, jFmtMrbDataVendas);
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgMrbVendaProdutos jDlgMrbVendaProdutos = new JDlgMrbVendaProdutos(null, true);
        jDlgMrbVendaProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
        JDlgMrbVendaProdutos jDlgMrbVendaProdutos = new JDlgMrbVendaProdutos(null, true);
        jDlgMrbVendaProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        JDlgMrbVendaProdutos jDlgMrbVendaProdutos = new JDlgMrbVendaProdutos(null, true);
        jDlgMrbVendaProdutos.setVisible(true);
        if (Util.perguntar("Deseja excluir o produto?") == true);
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    private void jCboMrbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboMrbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboMrbClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMrbVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMrbVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMrbVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMrbVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMrbVenda dialog = new JDlgMrbVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<MrbCliente> jCboMrbCliente;
    private javax.swing.JComboBox<MrbPagamento> jCboMrbPagamentos;
    private javax.swing.JFormattedTextField jFmtMrbDataVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPanelMrbPainel;
    private javax.swing.JTable jTblMrbTabela;
    private javax.swing.JTextField jTxtMrbCodigo;
    private javax.swing.JTextField jTxtMrbStatus;
    private javax.swing.JTextField jTxtMrbTipo;
    private javax.swing.JTextField jTxtMrbTotal;
    // End of variables declaration//GEN-END:variables
}
