/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class JFrmMrbPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPanel
     */
    public JFrmMrbPrincipal() {
        initComponents();
        setTitle("Sistema Venda de Horta");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnlMrbCadastro = new javax.swing.JMenu();
        jMnIMrbUsuario = new javax.swing.JMenuItem();
        jMnIMrbCliente = new javax.swing.JMenuItem();
        jMnIMrbProdutos = new javax.swing.JMenuItem();
        jMnIMrbPagamento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMnlMrbSair = new javax.swing.JMenuItem();
        jMnlMrbMovimento = new javax.swing.JMenu();
        jMnIMrbVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnlMrbCadastro.setText("Cadastro");

        jMnIMrbUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIMrbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/steve.png"))); // NOI18N
        jMnIMrbUsuario.setText("Usuário");
        jMnIMrbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIMrbUsuarioActionPerformed(evt);
            }
        });
        jMnlMrbCadastro.add(jMnIMrbUsuario);

        jMnIMrbCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIMrbCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creeper.png"))); // NOI18N
        jMnIMrbCliente.setText("Cliente");
        jMnIMrbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIMrbClienteActionPerformed(evt);
            }
        });
        jMnlMrbCadastro.add(jMnIMrbCliente);

        jMnIMrbProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIMrbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrot.png"))); // NOI18N
        jMnIMrbProdutos.setText("Produtos");
        jMnIMrbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIMrbProdutosActionPerformed(evt);
            }
        });
        jMnlMrbCadastro.add(jMnIMrbProdutos);

        jMnIMrbPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIMrbPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emerald.png"))); // NOI18N
        jMnIMrbPagamento.setText("Pagamento");
        jMnIMrbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIMrbPagamentoActionPerformed(evt);
            }
        });
        jMnlMrbCadastro.add(jMnIMrbPagamento);
        jMnlMrbCadastro.add(jSeparator1);

        JMnlMrbSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMnlMrbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tnt.png"))); // NOI18N
        JMnlMrbSair.setText("Sair");
        JMnlMrbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnlMrbSairActionPerformed(evt);
            }
        });
        jMnlMrbCadastro.add(JMnlMrbSair);

        jMenuBar1.add(jMnlMrbCadastro);

        jMnlMrbMovimento.setText("Movimento");

        jMnIMrbVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIMrbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apple.png"))); // NOI18N
        jMnIMrbVendas.setText("Vendas de Produtos");
        jMnIMrbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIMrbVendasActionPerformed(evt);
            }
        });
        jMnlMrbMovimento.add(jMnIMrbVendas);

        jMenuBar1.add(jMnlMrbMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnIMrbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIMrbVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnIMrbVendasActionPerformed

    private void jMnIMrbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIMrbUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgMrbUsuarios jDlgUsuario = new JDlgMrbUsuarios(this, true);
        jDlgUsuario.setVisible(true);
    }//GEN-LAST:event_jMnIMrbUsuarioActionPerformed

    private void jMnIMrbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIMrbClienteActionPerformed
        // TODO add your handling code here:
        JDlgMrbClientes jDlgCliente = new JDlgMrbClientes(this, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMnIMrbClienteActionPerformed

    private void jMnIMrbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIMrbProdutosActionPerformed
        // TODO add your handling code here:
        JDlgMrbProdutos jDlgProdutos = new JDlgMrbProdutos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnIMrbProdutosActionPerformed

    private void jMnIMrbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIMrbPagamentoActionPerformed
        // TODO add your handling code here:
        JDlgMrbPagamento jDlgPagamento = new JDlgMrbPagamento(this, true);
        jDlgPagamento.setVisible(true);
    }//GEN-LAST:event_jMnIMrbPagamentoActionPerformed

    private void JMnlMrbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnlMrbSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JMnlMrbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMrbPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMnlMrbSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnIMrbCliente;
    private javax.swing.JMenuItem jMnIMrbPagamento;
    private javax.swing.JMenuItem jMnIMrbProdutos;
    private javax.swing.JMenuItem jMnIMrbUsuario;
    private javax.swing.JMenuItem jMnIMrbVendas;
    private javax.swing.JMenu jMnlMrbCadastro;
    private javax.swing.JMenu jMnlMrbMovimento;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
