package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MrbCliente generated by hbm2java
 */
@Entity
@Table(name="mrb_cliente"
    ,catalog="sistema_venda_horta"
    , uniqueConstraints = @UniqueConstraint(columnNames="mrb_cpf") 
)
public class MrbCliente  implements java.io.Serializable {


     private int mrbIdCliente;
     private String mrbNome;
     private String mrbCpf;
     private String mrbRg;
     private int mrbSexo;
     private Date mrbDataNascimento;
     private String mrbEmail;
     private String mrbCep;
     private String mrbEndereco;
     private String mrbBairro;
     private String mrbComplemento;
     private String mrbTelefoneResidencial;
     private String mrbCelular;
     private String mrbNumero;
     private String mrbRua;
     private String mrbAtivo;


    public MrbCliente() {
    }

	
    public MrbCliente(int mrbIdCliente, String mrbNome, String mrbCpf, String mrbRg, int mrbSexo, Date mrbDataNascimento, String mrbEmail, String mrbCep, String mrbEndereco, String mrbBairro, String mrbComplemento, String mrbTelefoneResidencial, String mrbCelular, String mrbNumero, String mrbRua, String mrbAtivo) {
        this.mrbIdCliente = mrbIdCliente;
        this.mrbNome = mrbNome;
        this.mrbCpf = mrbCpf;
        this.mrbRg = mrbRg;
        this.mrbSexo = mrbSexo;
        this.mrbDataNascimento = mrbDataNascimento;
        this.mrbEmail = mrbEmail;
        this.mrbCep = mrbCep;
        this.mrbEndereco = mrbEndereco;
        this.mrbBairro = mrbBairro;
        this.mrbComplemento = mrbComplemento;
        this.mrbTelefoneResidencial = mrbTelefoneResidencial;
        this.mrbCelular = mrbCelular;
        this.mrbNumero = mrbNumero;
        this.mrbRua = mrbRua;
        this.mrbAtivo = mrbAtivo;
    }
   
     @Id 

    
    @Column(name="mrb_idCliente", unique=true, nullable=false)
    public int getMrbIdCliente() {
        return this.mrbIdCliente;
    }
    
    public void setMrbIdCliente(int mrbIdCliente) {
        this.mrbIdCliente = mrbIdCliente;
    }

    
    @Column(name="mrb_nome", nullable=false, length=100)
    public String getMrbNome() {
        return this.mrbNome;
    }
    
    public void setMrbNome(String mrbNome) {
        this.mrbNome = mrbNome;
    }

    
    @Column(name="mrb_cpf", unique=true, nullable=false, length=14)
    public String getMrbCpf() {
        return this.mrbCpf;
    }
    
    public void setMrbCpf(String mrbCpf) {
        this.mrbCpf = mrbCpf;
    }

    
    @Column(name="mrb_rg", nullable=false, length=10)
    public String getMrbRg() {
        return this.mrbRg;
    }
    
    public void setMrbRg(String mrbRg) {
        this.mrbRg = mrbRg;
    }

    
    @Column(name="mrb_sexo", nullable=false, length=1)
    public int getMrbSexo() {
        return this.mrbSexo;
    }
    
    public void setMrbSexo(int mrbSexo) {
        this.mrbSexo = mrbSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataNascimento", nullable=false, length=10)
    public Date getMrbDataNascimento() {
        return this.mrbDataNascimento;
    }
    
    public void setMrbDataNascimento(Date mrbDataNascimento) {
        this.mrbDataNascimento = mrbDataNascimento;
    }

    
    @Column(name="mrb_email", nullable=false, length=80)
    public String getMrbEmail() {
        return this.mrbEmail;
    }
    
    public void setMrbEmail(String mrbEmail) {
        this.mrbEmail = mrbEmail;
    }

    
    @Column(name="mrb_cep", nullable=false, length=9)
    public String getMrbCep() {
        return this.mrbCep;
    }
    
    public void setMrbCep(String mrbCep) {
        this.mrbCep = mrbCep;
    }

    
    @Column(name="mrb_endereco", nullable=false, length=50)
    public String getMrbEndereco() {
        return this.mrbEndereco;
    }
    
    public void setMrbEndereco(String mrbEndereco) {
        this.mrbEndereco = mrbEndereco;
    }

    
    @Column(name="mrb_bairro", nullable=false, length=30)
    public String getMrbBairro() {
        return this.mrbBairro;
    }
    
    public void setMrbBairro(String mrbBairro) {
        this.mrbBairro = mrbBairro;
    }

    
    @Column(name="mrb_complemento", nullable=false, length=50)
    public String getMrbComplemento() {
        return this.mrbComplemento;
    }
    
    public void setMrbComplemento(String mrbComplemento) {
        this.mrbComplemento = mrbComplemento;
    }

    
    @Column(name="mrb_telefoneResidencial", nullable=false, length=10)
    public String getMrbTelefoneResidencial() {
        return this.mrbTelefoneResidencial;
    }
    
    public void setMrbTelefoneResidencial(String mrbTelefoneResidencial) {
        this.mrbTelefoneResidencial = mrbTelefoneResidencial;
    }

    
    @Column(name="mrb_celular", nullable=false, length=10)
    public String getMrbCelular() {
        return this.mrbCelular;
    }
    
    public void setMrbCelular(String mrbCelular) {
        this.mrbCelular = mrbCelular;
    }

    
    @Column(name="mrb_numero", nullable=false, length=10)
    public String getMrbNumero() {
        return this.mrbNumero;
    }
    
    public void setMrbNumero(String mrbNumero) {
        this.mrbNumero = mrbNumero;
    }

    
    @Column(name="mrb_rua", nullable=false, length=30)
    public String getMrbRua() {
        return this.mrbRua;
    }
    
    public void setMrbRua(String mrbRua) {
        this.mrbRua = mrbRua;
    }

    
    @Column(name="mrb_ativo", nullable=false, length=1)
    public String getMrbAtivo() {
        return this.mrbAtivo;
    }
    
    public void setMrbAtivo(String mrbAtivo) {
        this.mrbAtivo = mrbAtivo;
    }

}


