package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MrbProdutos generated by hbm2java
 */
@Entity
@Table(name="mrb_produtos"
    ,catalog="sistema_venda_horta"
)
public class MrbProdutos  implements java.io.Serializable {


     private int mrbIdProduto;
     private String mrbNomeProduto;
     private BigDecimal mrbPreco;
     private String mrbTipo;
     private Date mrbDataColheita;
     private BigDecimal mrbPeso;
     private String mrbUnidadeMedida;
     private Set mrbVendaprodutoses = new HashSet(0);

    public MrbProdutos() {
    }

	
    public MrbProdutos(int mrbIdProduto, String mrbNomeProduto, BigDecimal mrbPreco, String mrbTipo, Date mrbDataColheita, BigDecimal mrbPeso, String mrbUnidadeMedida) {
        this.mrbIdProduto = mrbIdProduto;
        this.mrbNomeProduto = mrbNomeProduto;
        this.mrbPreco = mrbPreco;
        this.mrbTipo = mrbTipo;
        this.mrbDataColheita = mrbDataColheita;
        this.mrbPeso = mrbPeso;
        this.mrbUnidadeMedida = mrbUnidadeMedida;
    }
    public MrbProdutos(int mrbIdProduto, String mrbNomeProduto, BigDecimal mrbPreco, String mrbTipo, Date mrbDataColheita, BigDecimal mrbPeso, String mrbUnidadeMedida, Set mrbVendaprodutoses) {
       this.mrbIdProduto = mrbIdProduto;
       this.mrbNomeProduto = mrbNomeProduto;
       this.mrbPreco = mrbPreco;
       this.mrbTipo = mrbTipo;
       this.mrbDataColheita = mrbDataColheita;
       this.mrbPeso = mrbPeso;
       this.mrbUnidadeMedida = mrbUnidadeMedida;
       this.mrbVendaprodutoses = mrbVendaprodutoses;
    }
   
     @Id 

    
    @Column(name="mrb_idProduto", unique=true, nullable=false)
    public int getMrbIdProduto() {
        return this.mrbIdProduto;
    }
    
    public void setMrbIdProduto(int mrbIdProduto) {
        this.mrbIdProduto = mrbIdProduto;
    }

    
    @Column(name="mrb_nomeProduto", nullable=false, length=50)
    public String getMrbNomeProduto() {
        return this.mrbNomeProduto;
    }
    
    public void setMrbNomeProduto(String mrbNomeProduto) {
        this.mrbNomeProduto = mrbNomeProduto;
    }

    
    @Column(name="mrb_preco", nullable=false, precision=5)
    public BigDecimal getMrbPreco() {
        return this.mrbPreco;
    }
    
    public void setMrbPreco(BigDecimal mrbPreco) {
        this.mrbPreco = mrbPreco;
    }

    
    @Column(name="mrb_tipo", nullable=false, length=100)
    public String getMrbTipo() {
        return this.mrbTipo;
    }
    
    public void setMrbTipo(String mrbTipo) {
        this.mrbTipo = mrbTipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataColheita", nullable=false, length=10)
    public Date getMrbDataColheita() {
        return this.mrbDataColheita;
    }
    
    public void setMrbDataColheita(Date mrbDataColheita) {
        this.mrbDataColheita = mrbDataColheita;
    }

    
    @Column(name="mrb_peso", nullable=false, precision=5)
    public BigDecimal getMrbPeso() {
        return this.mrbPeso;
    }
    
    public void setMrbPeso(BigDecimal mrbPeso) {
        this.mrbPeso = mrbPeso;
    }

    
    @Column(name="mrb_unidadeMedida", nullable=false, length=10)
    public String getMrbUnidadeMedida() {
        return this.mrbUnidadeMedida;
    }
    
    public void setMrbUnidadeMedida(String mrbUnidadeMedida) {
        this.mrbUnidadeMedida = mrbUnidadeMedida;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mrbProdutos")
    public Set getMrbVendaprodutoses() {
        return this.mrbVendaprodutoses;
    }
    
    public void setMrbVendaprodutoses(Set mrbVendaprodutoses) {
        this.mrbVendaprodutoses = mrbVendaprodutoses;
    }




}


