package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MrbPagamento generated by hbm2java
 */
@Entity
@Table(name="mrb_pagamento"
    ,catalog="sistema_venda_horta"
)
public class MrbPagamento  implements java.io.Serializable {


     private int mrbIdPagamento;
     private int mrbTipoPagamento;
     private int mrbStatusPagamento;
     private Date mrbDataPagamento;
     private double mrbValorPago;
     private String mrbCpf;
     private String mrbConfirmacao;

    public MrbPagamento() {
    }

	
    public MrbPagamento(int mrbIdPagamento, int mrbTipoPagamento, int mrbStatusPagamento, Date mrbDataPagamento, double mrbValorPago, String mrbCpf, String mrbConfirmacao) {
        this.mrbIdPagamento = mrbIdPagamento;
        this.mrbTipoPagamento = mrbTipoPagamento;
        this.mrbStatusPagamento = mrbStatusPagamento;
        this.mrbDataPagamento = mrbDataPagamento;
        this.mrbValorPago = mrbValorPago;
        this.mrbCpf = mrbCpf;
        this.mrbConfirmacao = mrbConfirmacao;
    }

     @Id 

    
    @Column(name="mrb_idPagamento", unique=true, nullable=false)
    public int getMrbIdPagamento() {
        return this.mrbIdPagamento;
    }
    
    public void setMrbIdPagamento(int mrbIdPagamento) {
        this.mrbIdPagamento = mrbIdPagamento;
    }

    
    @Column(name="mrb_tipoPagamento", nullable=false, length=50)
    public int getMrbTipoPagamento() {
        return this.mrbTipoPagamento;
    }
    
    public void setMrbTipoPagamento(int mrbTipoPagamento) {
        this.mrbTipoPagamento = mrbTipoPagamento;
    }

    
    @Column(name="mrb_statusPagamento", nullable=false, length=1)
    public int getMrbStatusPagamento() {
        return this.mrbStatusPagamento;
    }
    
    public void setMrbStatusPagamento(int mrbStatusPagamento) {
        this.mrbStatusPagamento = mrbStatusPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataPagamento", nullable=false, length=10)
    public Date getMrbDataPagamento() {
        return this.mrbDataPagamento;
    }
    
    public void setMrbDataPagamento(Date mrbDataPagamento) {
        this.mrbDataPagamento = mrbDataPagamento;
    }

    
    @Column(name="mrb_valorPago", nullable=false, precision=5)
    public double getMrbValorPago() {
        return this.mrbValorPago;
    }
    
    public void setMrbValorPago(double mrbValorPago) {
        this.mrbValorPago = mrbValorPago;
    }

    
    @Column(name="mrb_cpf", nullable=false, length=14)
    public String getMrbCpf() {
        return this.mrbCpf;
    }
    
    public void setMrbCpf(String mrbCpf) {
        this.mrbCpf = mrbCpf;
    }

    
    @Column(name="mrb_confirmacao", nullable=false, length=10)
    public String getMrbConfirmacao() {
        return this.mrbConfirmacao;
    }
    
    public void setMrbConfirmacao(String mrbConfirmacao) {
        this.mrbConfirmacao = mrbConfirmacao;
    }

}


