package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MrbProdutos generated by hbm2java
 */
@Entity
@Table(name="mrb_produtos"
    ,catalog="sistema_venda_horta"
)
public class MrbProdutos  implements java.io.Serializable {


     private int mrbIdProduto;
     private String mrbNomeProduto;
     private double mrbPreco;
     private int mrbTipo;
     private Date mrbDataColheita;
     private double mrbPeso;
     private int mrbUnidadeMedida;

    public MrbProdutos() {
    }

	
    public MrbProdutos(int mrbIdProduto, String mrbNomeProduto, double mrbPreco, int mrbTipo, Date mrbDataColheita, double mrbPeso, int mrbUnidadeMedida) {
        this.mrbIdProduto = mrbIdProduto;
        this.mrbNomeProduto = mrbNomeProduto;
        this.mrbPreco = mrbPreco;
        this.mrbTipo = mrbTipo;
        this.mrbDataColheita = mrbDataColheita;
        this.mrbPeso = mrbPeso;
        this.mrbUnidadeMedida = mrbUnidadeMedida;
    }

     @Id 

    
    @Column(name="mrb_idProduto", unique=true, nullable=false)
    public int getMrbIdProduto() {
        return this.mrbIdProduto;
    }
    
    public void setMrbIdProduto(int mrbIdProduto) {
        this.mrbIdProduto = mrbIdProduto;
    }

    
    @Column(name="mrb_nomeProduto", nullable=false, length=50)
    public String getMrbNomeProduto() {
        return this.mrbNomeProduto;
    }
    
    public void setMrbNomeProduto(String mrbNomeProduto) {
        this.mrbNomeProduto = mrbNomeProduto;
    }

    
    @Column(name="mrb_preco", nullable=false, precision=5)
    public double getMrbPreco() {
        return this.mrbPreco;
    }
    
    public void setMrbPreco(double mrbPreco) {
        this.mrbPreco = mrbPreco;
    }

    
    @Column(name="mrb_tipo", nullable=false, length=100)
    public int getMrbTipo() {
        return this.mrbTipo;
    }
    
    public void setMrbTipo(int mrbTipo) {
        this.mrbTipo = mrbTipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataColheita", nullable=false, length=10)
    public Date getMrbDataColheita() {
        return this.mrbDataColheita;
    }
    
    public void setMrbDataColheita(Date mrbDataColheita) {
        this.mrbDataColheita = mrbDataColheita;
    }

    
    @Column(name="mrb_peso", nullable=false, precision=5)
    public double getMrbPeso() {
        return this.mrbPeso;
    }
    
    public void setMrbPeso(double mrbPeso) {
        this.mrbPeso = mrbPeso;
    }

    
    @Column(name="mrb_unidadeMedida", nullable=false, length=10)
    public int getMrbUnidadeMedida() {
        return this.mrbUnidadeMedida;
    }
    
    public void setMrbUnidadeMedida(int mrbUnidadeMedida) {
        this.mrbUnidadeMedida = mrbUnidadeMedida;
    }

}


