package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MrbUsuario generated by hbm2java
 */
@Entity
@Table(name="mrb_usuario"
    ,catalog="sistema_venda_horta"
    , uniqueConstraints = @UniqueConstraint(columnNames="mrb_cpf") 
)
public class MrbUsuario  implements java.io.Serializable {


     private int mrbIdUsuario;
     private String mrbNome;
     private Date mrbDataNascimento;
     private String mrbCpf;
     private String mrbSenha;
     private String mrbApelido;
     private String mrbAtivo;
     private int mrbNivel;

    public MrbUsuario() {
    }

    public MrbUsuario(int mrbIdUsuario, String mrbNome, Date mrbDataNascimento, String mrbCpf, String mrbSenha, String mrbApelido, String mrbAtivo, int mrbNivel) {
       this.mrbIdUsuario = mrbIdUsuario;
       this.mrbNome = mrbNome;
       this.mrbDataNascimento = mrbDataNascimento;
       this.mrbCpf = mrbCpf;
       this.mrbSenha = mrbSenha;
       this.mrbApelido = mrbApelido;
       this.mrbAtivo = mrbAtivo;
       this.mrbNivel = mrbNivel;
    }
   
     @Id 

    
    @Column(name="mrb_idUsuario", unique=true, nullable=false)
    public int getMrbIdUsuario() {
        return this.mrbIdUsuario;
    }
    
    public void setMrbIdUsuario(int mrbIdUsuario) {
        this.mrbIdUsuario = mrbIdUsuario;
    }

    
    @Column(name="mrb_nome", nullable=false, length=50)
    public String getMrbNome() {
        return this.mrbNome;
    }
    
    public void setMrbNome(String mrbNome) {
        this.mrbNome = mrbNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataNascimento", nullable=false, length=10)
    public Date getMrbDataNascimento() {
        return this.mrbDataNascimento;
    }
    
    public void setMrbDataNascimento(Date mrbDataNascimento) {
        this.mrbDataNascimento = mrbDataNascimento;
    }

    
    @Column(name="mrb_cpf", unique=true, nullable=false, length=14)
    public String getMrbCpf() {
        return this.mrbCpf;
    }
    
    public void setMrbCpf(String mrbCpf) {
        this.mrbCpf = mrbCpf;
    }

    
    @Column(name="mrb_senha", nullable=false, length=20)
    public String getMrbSenha() {
        return this.mrbSenha;
    }
    
    public void setMrbSenha(String mrbSenha) {
        this.mrbSenha = mrbSenha;
    }

    
    @Column(name="mrb_apelido", nullable=false, length=30)
    public String getMrbApelido() {
        return this.mrbApelido;
    }
    
    public void setMrbApelido(String mrbApelido) {
        this.mrbApelido = mrbApelido;
    }

    
    @Column(name="mrb_ativo", nullable=false, length=1)
    public String getMrbAtivo() {
        return this.mrbAtivo;
    }
    
    public void setMrbAtivo(String mrbAtivo) {
        this.mrbAtivo = mrbAtivo;
    }

    
    @Column(name="mrb_nivel", nullable=false)
    public int getMrbNivel() {
        return this.mrbNivel;
    }
    
    public void setMrbNivel(int mrbNivel) {
        this.mrbNivel = mrbNivel;
    }




}


