package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MrbVenda generated by hbm2java
 */
@Entity
@Table(name="mrb_venda"
    ,catalog="sistema_venda_horta"
)
public class MrbVenda  implements java.io.Serializable {


     private int mrbIdVenda;
     private MrbCliente mrbCliente;
     private MrbPagamento mrbPagamento;
     private Date mrbDataVenda;
     private double mrbValorTotal;
     private String mrbStatusVenda;
     private String mrbTipoEntrega;

    public MrbVenda() {
    }

	
    public MrbVenda(int mrbIdVenda, MrbCliente mrbCliente, MrbPagamento mrbPagamento, Date mrbDataVenda, double mrbValorTotal, String mrbStatusVenda, String mrbTipoEntrega) {
        this.mrbIdVenda = mrbIdVenda;
        this.mrbCliente = mrbCliente;
        this.mrbPagamento = mrbPagamento;
        this.mrbDataVenda = mrbDataVenda;
        this.mrbValorTotal = mrbValorTotal;
        this.mrbStatusVenda = mrbStatusVenda;
        this.mrbTipoEntrega = mrbTipoEntrega;
    }
   
     @Id 

    
    @Column(name="mrb_idVenda", unique=true, nullable=false)
    public int getMrbIdVenda() {
        return this.mrbIdVenda;
    }
    
    public void setMrbIdVenda(int mrbIdVenda) {
        this.mrbIdVenda = mrbIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mrb_fieldCliente", nullable=false)
    public MrbCliente getMrbCliente() {
        return this.mrbCliente;
    }
    
    public void setMrbCliente(MrbCliente mrbCliente) {
        this.mrbCliente = mrbCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mrb_fieldPagamento", nullable=false)
    public MrbPagamento getMrbPagamento() {
        return this.mrbPagamento;
    }
    
    public void setMrbPagamento(MrbPagamento mrbPagamento) {
        this.mrbPagamento = mrbPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mrb_dataVenda", nullable=false, length=10)
    public Date getMrbDataVenda() {
        return this.mrbDataVenda;
    }
    
    public void setMrbDataVenda(Date mrbDataVenda) {
        this.mrbDataVenda = mrbDataVenda;
    }

    
    @Column(name="mrb_valorTotal", nullable=false, precision=10)
    public double getMrbValorTotal() {
        return this.mrbValorTotal;
    }
    
    public void setMrbValorTotal(double mrbValorTotal) {
        this.mrbValorTotal = mrbValorTotal;
    }

    
    @Column(name="mrb_statusVenda", nullable=false, length=1)
    public String getMrbStatusVenda() {
        return this.mrbStatusVenda;
    }
    
    public void setMrbStatusVenda(String mrbStatusVenda) {
        this.mrbStatusVenda = mrbStatusVenda;
    }

    
    @Column(name="mrb_tipoEntrega", nullable=false, length=50)
    public String getMrbTipoEntrega() {
        return this.mrbTipoEntrega;
    }
    
    public void setMrbTipoEntrega(String mrbTipoEntrega) {
        this.mrbTipoEntrega = mrbTipoEntrega;
    }

}


