package bean;
// Generated Oct 14, 2025 8:56:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MrbVendaprodutos generated by hbm2java
 */
@Entity
@Table(name="mrb_vendaprodutos"
    ,catalog="sistema_venda_horta"
)
public class MrbVendaprodutos  implements java.io.Serializable {


     private int mrbIdVendaProduto;
     private MrbProdutos mrbProdutos;
     private MrbVenda mrbVenda;
     private int mrbQuantidade;
     private double mrbPrecoUnitario;
     private String mrbUnidadeVenda;

    public MrbVendaprodutos() {
    }

    public MrbVendaprodutos(int mrbIdVendaProduto, MrbProdutos mrbProdutos, MrbVenda mrbVenda, int mrbQuantidade, double mrbPrecoUnitario, String mrbUnidadeVenda) {
       this.mrbIdVendaProduto = mrbIdVendaProduto;
       this.mrbProdutos = mrbProdutos;
       this.mrbVenda = mrbVenda;
       this.mrbQuantidade = mrbQuantidade;
       this.mrbPrecoUnitario = mrbPrecoUnitario;
       this.mrbUnidadeVenda = mrbUnidadeVenda;
    }
   
     @Id 

    
    @Column(name="mrb_idVendaProduto", unique=true, nullable=false)
    public int getMrbIdVendaProduto() {
        return this.mrbIdVendaProduto;
    }
    
    public void setMrbIdVendaProduto(int mrbIdVendaProduto) {
        this.mrbIdVendaProduto = mrbIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mrb_fieldProduto", nullable=false)
    public MrbProdutos getMrbProdutos() {
        return this.mrbProdutos;
    }
    
    public void setMrbProdutos(MrbProdutos mrbProdutos) {
        this.mrbProdutos = mrbProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mrb_fieldVenda", nullable=false)
    public MrbVenda getMrbVenda() {
        return this.mrbVenda;
    }
    
    public void setMrbVenda(MrbVenda mrbVenda) {
        this.mrbVenda = mrbVenda;
    }

    
    @Column(name="mrb_quantidade", nullable=false)
    public int getMrbQuantidade() {
        return this.mrbQuantidade;
    }
    
    public void setMrbQuantidade(int mrbQuantidade) {
        this.mrbQuantidade = mrbQuantidade;
    }

    
    @Column(name="mrb_precoUnitario", nullable=false, precision=5)
    public double getMrbPrecoUnitario() {
        return this.mrbPrecoUnitario;
    }
    
    public void setMrbPrecoUnitario(double mrbPrecoUnitario) {
        this.mrbPrecoUnitario = mrbPrecoUnitario;
    }

    
    @Column(name="mrb_unidadeVenda", nullable=false, length=10)
    public String getMrbUnidadeVenda() {
        return this.mrbUnidadeVenda;
    }
    
    public void setMrbUnidadeVenda(String mrbUnidadeVenda) {
        this.mrbUnidadeVenda = mrbUnidadeVenda;
    }




}


